### ISSUE TITLE
unexpected IRanges ends returned by to_pandas()

### ISSUE THREAD

**Issue by carl-** [BiocPy/IRanges#14]
https://github.com/BiocPy/IRanges/blob/36b908cb64bf46a95a0a8d9c95c05de05e8f49a0/src/iranges/IRanges.py#L2085

change:

_ends = self.get_end

to:
_ends = self.get_end()

will get the expected  values

**Comment by jkanche** [comment]
Thanks @carl- for reporting the issue! v0.2.1 should correct this. Let me know if you run into more issues!
